const exerciseDatabase = [
    { name: "Barbell Bench Press", category: "Chest", equipment: "Barbell" },
    { name: "Barbell Incline Press", category: "Chest", equipment: "Barbell" },
    { name: "Dumbbell Bench Press", category: "Chest", equipment: "Dumbbell" },
    { name: "Dumbbell Incline Press", category: "Chest", equipment: "Dumbbell" },
    { name: "Dumbbell Flyes", category: "Chest", equipment: "Dumbbell" },
    { name: "Bodyweight Push-Up", category: "Chest", equipment: "Bodyweight" },
    { name: "Bodyweight Dips", category: "Chest", equipment: "Bodyweight" },
    { name: "Cable Crossover", category: "Chest", equipment: "Cable" },
    { name: "Machine Chest Press", category: "Chest", equipment: "Machine" },
    { name: "Machine Pec Deck", category: "Chest", equipment: "Machine" },
    
    { name: "Barbell Squat", category: "Legs", equipment: "Barbell" },
    { name: "Barbell Front Squat", category: "Legs", equipment: "Barbell" },
    { name: "Barbell Romanian Deadlift", category: "Legs", equipment: "Barbell" },
    { name: "Dumbbell Bulgarian Split Squat", category: "Legs", equipment: "Dumbbell" },
    { name: "Dumbbell Romanian Deadlift", category: "Legs", equipment: "Dumbbell" },
    { name: "Dumbbell Lunges", category: "Legs", equipment: "Dumbbell" },
    { name: "Machine Leg Press", category: "Legs", equipment: "Machine" },
    { name: "Machine Hack Squat", category: "Legs", equipment: "Machine" },
    { name: "Machine Leg Extension", category: "Legs", equipment: "Machine" },
    { name: "Machine Seated Leg Curl", category: "Legs", equipment: "Machine" },
    { name: "Machine Lying Leg Curl", category: "Legs", equipment: "Machine" },
    { name: "Machine Calf Raises", category: "Legs", equipment: "Machine" },
    
    { name: "Barbell Deadlift", category: "Back", equipment: "Barbell" },
    { name: "Barbell Row", category: "Back", equipment: "Barbell" },
    { name: "Bodyweight Pull-Up", category: "Back", equipment: "Bodyweight" },
    { name: "Bodyweight Chin-Up", category: "Back", equipment: "Bodyweight" },
    { name: "Cable Lat Pulldown", category: "Back", equipment: "Cable" },
    { name: "Cable Seated Row", category: "Back", equipment: "Cable" },
    { name: "Cable Straight Arm Pulldown", category: "Back", equipment: "Cable" },
    { name: "Dumbbell Single Arm Row", category: "Back", equipment: "Dumbbell" },
    { name: "Dumbbell Pullover", category: "Back", equipment: "Dumbbell" },
    { name: "Machine T-Bar Row", category: "Back", equipment: "Machine" },
    { name: "Machine Row", category: "Back", equipment: "Machine" },
    
    { name: "Barbell Overhead Press", category: "Shoulders", equipment: "Barbell" },
    { name: "Barbell Shrugs", category: "Shoulders", equipment: "Barbell" },
    { name: "Dumbbell Shoulder Press", category: "Shoulders", equipment: "Dumbbell" },
    { name: "Dumbbell Lateral Raise", category: "Shoulders", equipment: "Dumbbell" },
    { name: "Dumbbell Front Raise", category: "Shoulders", equipment: "Dumbbell" },
    { name: "Dumbbell Shrugs", category: "Shoulders", equipment: "Dumbbell" },
    { name: "Cable Lateral Raise", category: "Shoulders", equipment: "Cable" },
    { name: "Cable Face Pull", category: "Shoulders", equipment: "Cable" },
    { name: "Machine Shoulder Press", category: "Shoulders", equipment: "Machine" },
    { name: "Machine Reverse Pec Deck", category: "Shoulders", equipment: "Machine" },
    
    { name: "Barbell Bicep Curl", category: "Arms", equipment: "Barbell" },
    { name: "Barbell Skullcrusher", category: "Arms", equipment: "Barbell" },
    { name: "Barbell Close Grip Bench", category: "Arms", equipment: "Barbell" },
    { name: "Dumbbell Bicep Curl", category: "Arms", equipment: "Dumbbell" },
    { name: "Dumbbell Hammer Curl", category: "Arms", equipment: "Dumbbell" },
    { name: "Dumbbell Overhead Tricep Extension", category: "Arms", equipment: "Dumbbell" },
    { name: "Cable Bicep Curl", category: "Arms", equipment: "Cable" },
    { name: "Cable Tricep Pushdown", category: "Arms", equipment: "Cable" },
    { name: "Cable Overhead Tricep Extension", category: "Arms", equipment: "Cable" },
    { name: "Machine Preacher Curl", category: "Arms", equipment: "Machine" },
    { name: "Machine Tricep Extension", category: "Arms", equipment: "Machine" },
    
    { name: "Bodyweight Plank", category: "Core", equipment: "Bodyweight" },
    { name: "Bodyweight Crunch", category: "Core", equipment: "Bodyweight" },
    { name: "Bodyweight Hanging Leg Raise", category: "Core", equipment: "Bodyweight" },
    { name: "Bodyweight Russian Twist", category: "Core", equipment: "Bodyweight" },
    { name: "Cable Crunch", category: "Core", equipment: "Cable" },
    { name: "Machine Ab Wheel Rollout", category: "Core", equipment: "Machine" }
].sort((a, b) => a.name.localeCompare(b.name));
